### ISSUE TITLE
Please add ion-refresher and ion-infinite-scroll

### ISSUE THREAD

**Issue by osben** [narendrasinghrathore/todo_app_ionic#2]
Please add these components as you would share them with beautiful and clear code. So say, best practices

ps I look after your repository and find useful techniques and practices for myself.

**Comment by narendrasinghrathore** [comment]
Thanks  @osben 

>  I look after your repository and find useful techniques and practices for myself

As ion-refresher and ion-infinite-scroll are helpful when we are getting data from online server and limiting the data on each api call. ( for implementing paging ).

But in our case, we are using ionic-storage, so data will be available to user without need of server.

Also suppose you are using installing your app in different device, so initially it load data ( if any  ) to our local storage in background.

App will only use local storage for any CRUD operations and sync in background to server when it's online again or called manually yo sync which i will be adding in next coming commits.

Also for now it will only display data for selected day, and it wouldn't be exceeding ( for.eg like 500-1000 items in a day 🚚).
To display around 100 items in list doesn't need as we are using local storage.

Regards.

**Comment by narendrasinghrathore** [comment]
@osben ion-refresher is added. ✌
